### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test5@test.com",
    "password": "password"
}

### Login
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test3@test.com",
    "password": "password"
}

### Signout
POST http://localhost:3000/auth/signout

### Get the current User
GET http://localhost:3000/auth/whoami

### Find a user
GET http://localhost:3000/auth/2


### Find by email
GET http://localhost:3000/auth?email=test@test.com

### Update a user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "password": "updatedpassword"
}


### Remove a user
DELETE http://localhost:3000/auth/3
