### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "password"
}

### Find a user
GET http://localhost:3000/auth/132


### Find by email
GET http://localhost:3000/auth?email=test1@test.com

### Update a user
PATCH http://localhost:3000/auth/2422
Content-Type: application/json

{
    "password": "updatedpassword"
}


### Remove a user
DELETE http://localhost:3000/auth/3
